use std::collections::{BTreeMap, HashSet};
use std::io::Write;
use std::path::{Path, PathBuf};
use std::sync::OnceLock;

use tauri::Manager;

const ARIA2_OPTIONS_JSON: &str = include_str!("../../../src/shared/aria2Options.json");
const BUNDLED_CONFIG: &str = include_str!("../../binaries/aria2.conf");
const RUNTIME_CONFIG_DIR: &str = "engine";
const RUNTIME_CONFIG_FILE: &str = "aria2.conf";
const GENERATED_HEADER: &str =
    "# Generated by SeevvoDownloader. Do not edit.\n# Rebuilt before every Aria2 Next start.\n";

const PROXY_CLEAR_KEYS: &[&str] = &[
    "all-proxy",
    "all-proxy-user",
    "all-proxy-passwd",
    "http-proxy",
    "http-proxy-user",
    "http-proxy-passwd",
    "https-proxy",
    "https-proxy-user",
    "https-proxy-passwd",
    "ftp-proxy",
    "ftp-proxy-user",
    "ftp-proxy-passwd",
    "no-proxy",
];

const MANAGED_KEYS: &[&str] = &[
    "allow-remote-access",
    "enable-rpc",
    "input-file",
    "keep-sharing",
    "log",
    "log-file",
    "log-level",
    "log-max-files",
    "log-max-size",
    "quiet",
    "rpc-allow-origin-all",
    "rpc-listen-all",
    "save-session",
];

#[derive(serde::Deserialize)]
struct Aria2Options {
    #[serde(rename = "engineOptions")]
    engine_options: Vec<String>,
    #[serde(rename = "nonHotReloadable")]
    non_hot_reloadable: Vec<String>,
}

fn aria2_options() -> &'static Aria2Options {
    static OPTIONS: OnceLock<Aria2Options> = OnceLock::new();
    OPTIONS.get_or_init(|| {
        serde_json::from_str(ARIA2_OPTIONS_JSON).expect("aria2Options.json is valid JSON")
    })
}

pub(crate) fn supported_engine_keys() -> &'static HashSet<&'static str> {
    static KEYS: OnceLock<HashSet<&'static str>> = OnceLock::new();
    KEYS.get_or_init(|| {
        aria2_options()
            .engine_options
            .iter()
            .map(String::as_str)
            .collect()
    })
}

pub(crate) fn non_hot_reloadable_keys() -> &'static HashSet<&'static str> {
    static KEYS: OnceLock<HashSet<&'static str>> = OnceLock::new();
    KEYS.get_or_init(|| {
        aria2_options()
            .non_hot_reloadable
            .iter()
            .map(String::as_str)
            .collect()
    })
}

#[derive(Clone, Copy)]
pub(crate) struct ManagedEngineConfig<'a> {
    pub session_path: &'a str,
    pub load_session: bool,
    pub log_file_path: &'a str,
    pub log_level: &'a str,
}

fn preserves_empty_value(key: &str) -> bool {
    PROXY_CLEAR_KEYS.contains(&key) || key == "seed-time"
}

fn config_bool(config: &serde_json::Value, key: &str) -> bool {
    config.get(key).is_some_and(|value| match value {
        serde_json::Value::Bool(value) => *value,
        serde_json::Value::String(value) => value == "true",
        _ => false,
    })
}

fn scalar_string(value: &serde_json::Value) -> Option<String> {
    match value {
        serde_json::Value::String(value) => Some(value.clone()),
        serde_json::Value::Number(value) => Some(value.to_string()),
        serde_json::Value::Bool(value) => Some(value.to_string()),
        _ => None,
    }
}

fn validate_option(key: &str, value: &str) -> Result<(), String> {
    if key.is_empty()
        || !key
            .chars()
            .all(|character| character.is_ascii_alphanumeric() || character == '-')
    {
        return Err(format!("Invalid Aria2 Next option name: {key}"));
    }
    if value.contains(['\r', '\n']) {
        return Err(format!("Aria2 Next option contains a line break: {key}"));
    }
    Ok(())
}

fn parse_config(input: &str) -> Result<BTreeMap<String, String>, String> {
    let mut options = BTreeMap::new();
    for (index, raw_line) in input.lines().enumerate() {
        let line = raw_line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let (key, value) = line
            .split_once('=')
            .ok_or_else(|| format!("Invalid bundled aria2.conf line {}", index + 1))?;
        let key = key.trim();
        let value = value.trim();
        validate_option(key, value)?;
        options.insert(key.to_string(), value.to_string());
    }
    Ok(options)
}

fn bundled_options() -> &'static BTreeMap<String, String> {
    static OPTIONS: OnceLock<BTreeMap<String, String>> = OnceLock::new();
    OPTIONS.get_or_init(|| parse_config(BUNDLED_CONFIG).expect("bundled aria2.conf is valid"))
}

fn insert_option(
    options: &mut BTreeMap<String, String>,
    key: &str,
    value: impl Into<String>,
) -> Result<(), String> {
    let value = value.into();
    validate_option(key, &value)?;
    options.insert(key.to_string(), value);
    Ok(())
}

pub(crate) fn build_runtime_config(
    config: &serde_json::Value,
    managed: ManagedEngineConfig<'_>,
) -> Result<String, String> {
    let mut options = bundled_options().clone();
    let keep_sharing = config_bool(config, "keep-sharing");
    let allow_remote_access = config_bool(config, "allow-remote-access");

    if let Some(config) = config.as_object() {
        for (key, value) in config {
            if !supported_engine_keys().contains(key.as_str())
                || MANAGED_KEYS.contains(&key.as_str())
            {
                continue;
            }

            let Some(value) = scalar_string(value) else {
                continue;
            };
            if value.is_empty() && !preserves_empty_value(key) {
                continue;
            }
            if keep_sharing && key == "seed-time" && !value.is_empty() {
                continue;
            }
            if key == "all-proxy" && value.to_ascii_lowercase().starts_with("socks") {
                log::warn!("Skipping unsupported proxy protocol for all-proxy");
                continue;
            }

            insert_option(&mut options, key, value)?;
        }
    }

    if keep_sharing {
        insert_option(&mut options, "seed-ratio", "0")?;
    }

    insert_option(&mut options, "enable-rpc", "true")?;
    insert_option(
        &mut options,
        "rpc-listen-all",
        allow_remote_access.to_string(),
    )?;
    insert_option(&mut options, "rpc-allow-origin-all", "true")?;
    insert_option(&mut options, "save-session", managed.session_path)?;
    if managed.load_session {
        insert_option(&mut options, "input-file", managed.session_path)?;
    } else {
        options.remove("input-file");
    }
    insert_option(&mut options, "log", managed.log_file_path)?;
    insert_option(&mut options, "log-level", managed.log_level)?;
    insert_option(
        &mut options,
        "log-max-size",
        crate::log_policy::MAX_LOG_FILE_SIZE.to_string(),
    )?;
    insert_option(
        &mut options,
        "log-max-files",
        crate::log_policy::MAX_LOG_FILES.to_string(),
    )?;
    insert_option(&mut options, "quiet", "true")?;

    let mut output = String::with_capacity(
        GENERATED_HEADER.len()
            + options
                .iter()
                .map(|(key, value)| key.len() + value.len() + 2)
                .sum::<usize>(),
    );
    output.push_str(GENERATED_HEADER);
    for (key, value) in options {
        output.push_str(&key);
        output.push('=');
        output.push_str(&value);
        output.push('\n');
    }
    Ok(output)
}

pub(crate) fn runtime_config_path(app: &tauri::AppHandle) -> Result<PathBuf, String> {
    Ok(app
        .path()
        .app_local_data_dir()
        .map_err(|error| format!("Failed to get app local data dir: {error}"))?
        .join(RUNTIME_CONFIG_DIR)
        .join(RUNTIME_CONFIG_FILE))
}

fn write_atomic(path: &Path, content: &str) -> Result<(), String> {
    let directory = path
        .parent()
        .ok_or_else(|| "Invalid runtime config path".to_string())?;
    std::fs::create_dir_all(directory)
        .map_err(|error| format!("Failed to create runtime config directory: {error}"))?;

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(directory, std::fs::Permissions::from_mode(0o700))
            .map_err(|error| format!("Failed to secure runtime config directory: {error}"))?;
    }

    let mut temporary = tempfile::NamedTempFile::new_in(directory)
        .map_err(|error| format!("Failed to create runtime config: {error}"))?;
    temporary
        .write_all(content.as_bytes())
        .map_err(|error| format!("Failed to write runtime config: {error}"))?;
    temporary
        .as_file_mut()
        .sync_all()
        .map_err(|error| format!("Failed to sync runtime config: {error}"))?;

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        temporary
            .as_file()
            .set_permissions(std::fs::Permissions::from_mode(0o600))
            .map_err(|error| format!("Failed to secure runtime config: {error}"))?;
    }

    temporary
        .persist(path)
        .map_err(|error| format!("Failed to replace runtime config: {}", error.error))?;
    Ok(())
}

pub(crate) fn generate_runtime_config(
    app: &tauri::AppHandle,
    config: &serde_json::Value,
    managed: ManagedEngineConfig<'_>,
) -> Result<PathBuf, String> {
    let content = build_runtime_config(config, managed)?;
    let path = runtime_config_path(app)?;
    write_atomic(&path, &content)?;
    log::info!(
        "generated runtime engine config: path={} bytes={}",
        super::path_to_safe_string(&path),
        content.len()
    );
    Ok(path)
}

pub(crate) fn runtime_config_args(path: &Path) -> Vec<String> {
    vec![format!("--conf-path={}", super::path_to_safe_string(path))]
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn managed<'a>() -> ManagedEngineConfig<'a> {
        ManagedEngineConfig {
            session_path: "/data/download.session",
            load_session: true,
            log_file_path: "/logs/aria2-next.log",
            log_level: "warn",
        }
    }

    fn option_value<'a>(content: &'a str, key: &str) -> Option<&'a str> {
        content.lines().find_map(|line| {
            let (candidate, value) = line.split_once('=')?;
            (candidate == key).then_some(value)
        })
    }

    #[test]
    fn runtime_config_merges_bundled_user_and_managed_options() {
        let content = build_runtime_config(
            &json!({
                "dir": "/downloads",
                "split": 16,
                "allow-remote-access": true,
                "rpc-secret": "secret"
            }),
            managed(),
        )
        .expect("build config");

        assert_eq!(option_value(&content, "disk-cache"), Some("64M"));
        assert_eq!(option_value(&content, "dir"), Some("/downloads"));
        assert_eq!(option_value(&content, "split"), Some("16"));
        assert_eq!(option_value(&content, "rpc-secret"), Some("secret"));
        assert_eq!(option_value(&content, "rpc-listen-all"), Some("true"));
        assert_eq!(
            option_value(&content, "save-session"),
            Some("/data/download.session")
        );
        assert_eq!(
            option_value(&content, "input-file"),
            Some("/data/download.session")
        );
    }

    #[test]
    fn runtime_config_ignores_unsupported_bt_tracker() {
        let tracker = (0..4000)
            .map(|index| format!("udp://tracker{index}.example:6969/announce"))
            .collect::<Vec<_>>()
            .join(",");
        assert!(tracker.len() > 100_000);

        let content = build_runtime_config(&json!({ "bt-tracker": tracker }), managed())
            .expect("build config");

        assert_eq!(option_value(&content, "bt-tracker"), None);
        assert!(!content.contains("bt-tracker="));
    }

    #[test]
    fn runtime_config_rejects_line_break_injection() {
        let error = build_runtime_config(
            &json!({ "user-agent": "safe\nenable-rpc=false" }),
            managed(),
        )
        .expect_err("line break must fail");

        assert!(error.contains("user-agent"));
    }

    #[test]
    fn runtime_config_rejects_unknown_and_managed_overrides() {
        let content = build_runtime_config(
            &json!({
                "not-an-option": "value",
                "log": "/user.log",
                "log-level": "debug"
            }),
            managed(),
        )
        .expect("build config");

        assert!(!content.contains("not-an-option"));
        assert_eq!(option_value(&content, "log"), Some("/logs/aria2-next.log"));
        assert_eq!(option_value(&content, "log-level"), Some("warn"));
    }

    #[test]
    fn runtime_config_applies_keep_sharing_policy() {
        let content = build_runtime_config(
            &json!({
                "keep-sharing": true,
                "seed-time": "60",
                "seed-ratio": "1.5"
            }),
            managed(),
        )
        .expect("build config");

        assert_eq!(option_value(&content, "seed-ratio"), Some("0"));
        assert_eq!(option_value(&content, "seed-time"), None);
        assert!(!content.contains("keep-sharing"));
    }

    #[test]
    fn runtime_config_omits_session_input_when_disabled() {
        let managed = ManagedEngineConfig {
            load_session: false,
            ..managed()
        };
        let content = build_runtime_config(&json!({}), managed).expect("build config");

        assert_eq!(option_value(&content, "input-file"), None);
    }

    #[test]
    fn runtime_config_preserves_empty_clear_values() {
        let content = build_runtime_config(
            &json!({
                "all-proxy": "",
                "all-proxy-user": ""
            }),
            managed(),
        )
        .expect("build config");

        assert_eq!(option_value(&content, "all-proxy"), Some(""));
        assert_eq!(option_value(&content, "all-proxy-user"), Some(""));
    }

    #[test]
    fn runtime_config_skips_unsupported_socks_proxy() {
        let content = build_runtime_config(
            &json!({ "all-proxy": "socks5://127.0.0.1:1080" }),
            managed(),
        )
        .expect("build config");

        assert_eq!(option_value(&content, "all-proxy"), None);
    }

    #[test]
    fn runtime_config_contains_each_option_once() {
        let content = build_runtime_config(
            &json!({
                "async-dns": true,
                "remote-time": false,
                "retry-wait": 5
            }),
            managed(),
        )
        .expect("build config");
        let keys = content
            .lines()
            .filter(|line| !line.starts_with('#'))
            .filter_map(|line| line.split_once('=').map(|(key, _)| key))
            .collect::<Vec<_>>();
        let unique = keys.iter().copied().collect::<HashSet<_>>();

        assert_eq!(keys.len(), unique.len());
        assert_eq!(option_value(&content, "async-dns"), Some("true"));
        assert_eq!(option_value(&content, "remote-time"), Some("false"));
        assert_eq!(option_value(&content, "retry-wait"), Some("5"));
    }

    #[test]
    fn atomic_write_replaces_existing_config_and_secures_it() {
        let directory = tempfile::tempdir().expect("tempdir");
        let path = directory.path().join("engine").join("aria2.conf");

        write_atomic(&path, "first=true\n").expect("initial write");
        write_atomic(&path, "second=true\n").expect("replacement write");

        assert_eq!(std::fs::read_to_string(&path).unwrap(), "second=true\n");
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            assert_eq!(
                std::fs::metadata(&path).unwrap().permissions().mode() & 0o777,
                0o600
            );
        }
    }
}
